name: Latest NFT Project website  workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs at 12 on Sundays
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "NFT_PROJECT_WEBSITE"
          feed_list: "https://dopegoblins.com/"